### ISSUE TITLE
SyntaxError: Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by DavidSpek** [smockle/homebridge-harmony-tv#11]
When trying to control my Nvidia Shield I get the following error:

```
/homebridge/node_modules/homebridge-harmony-tv-smockle/index.js:201
  const { deviceId } = JSON.parse(action);
                                           ^
SyntaxError: Unexpected token o in JSON at position 1
```

It seems like this is caused by parsing something that is already an object. I edited the line in index.js:

` const { deviceId } = (action);`

When sending a command to move or go back the service now doesn't crash and does move, however there are some other issues now. Other than the response being extremely slow, there seem to be network time-outs and other errors:

```
(node:1349) UnhandledPromiseRejectionWarning: Error: timeout
    at Timeout._onTimeout (/homebridge/node_modules/harmonyhub-api/dist/HarmonyHub.js:334:40)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:1349) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1349) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1349) UnhandledPromiseRejectionWarning: Error: timeout
    at Timeout._onTimeout (/homebridge/node_modules/harmonyhub-api/dist/HarmonyHub.js:334:40)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:1349) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1349) UnhandledPromiseRejectionWarning: Error: timeout
    at Timeout._onTimeout (/homebridge/node_modules/harmonyhub-api/dist/HarmonyHub.js:334:40)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:1349) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
error: Connection failed to the websocket: Error: socket hang up
(node:1349) UnhandledPromiseRejectionWarning: Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at Socket.socketCloseListener (_http_client.js:364:25)
    at Socket.emit (events.js:187:15)
    at TCP._handle.close (net.js:610:12)
(node:1349) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
error: Connection failed to the websocket: Error: socket hang up
(node:1349) UnhandledPromiseRejectionWarning: Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at Socket.socketCloseListener (_http_client.js:364:25)
    at Socket.emit (events.js:187:15)
    at TCP._handle.close (net.js:610:12)
(node:1349) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
error: Error: write after end {"stack":"Error [ERR_STREAM_WRITE_AFTER_END]: write after end\n    at writeAfterEnd (_stream_writable.js:243:12)\n    at Socket.Writable.write (_stream_writable.js:291:5)\n    at WebSocketConnection.sendFrame (/homebridge/node_modules/websocket/lib/WebSocketConnection.js:859:31)\n    at WebSocketConnection.fragmentAndSend (/homebridge/node_modules/websocket/lib/WebSocketConnection.js:795:14)\n    at WebSocketConnection.sendUTF (/homebridge/node_modules/websocket/lib/WebSocketConnection.js:735:10)\n    at HarmonyHub.sendRequest (/homebridge/node_modules/harmonyhub-api/dist/HarmonyHub.js:275:23)\n    at HarmonyHub.sendCommand (/homebridge/node_modules/harmonyhub-api/dist/HarmonyHub.js:131:14)\n    at hub.connect.then (/homebridge/node_modules/homebridge-harmony-tv-smockle/index.js:203:14)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
(node:1349) UnhandledPromiseRejectionWarning: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:243:12)
    at Socket.Writable.write (_stream_writable.js:291:5)
    at WebSocketConnection.sendFrame (/homebridge/node_modules/websocket/lib/WebSocketConnection.js:859:31)
    at WebSocketConnection.fragmentAndSend (/homebridge/node_modules/websocket/lib/WebSocketConnection.js:795:14)
    at WebSocketConnection.sendUTF (/homebridge/node_modules/websocket/lib/WebSocketConnection.js:735:10)
    at HarmonyHub.sendRequest (/homebridge/node_modules/harmonyhub-api/dist/HarmonyHub.js:275:23)
    at HarmonyHub.sendCommand (/homebridge/node_modules/harmonyhub-api/dist/HarmonyHub.js:131:14)
    at hub.connect.then (/homebridge/node_modules/homebridge-harmony-tv-smockle/index.js:203:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1349) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
error: Error: write after end {"stack":"Error [ERR_STREAM_WRITE_AFTER_END]: write after end\n    at writeAfterEnd (_stream_writable.js:243:12)\n    at Socket.Writable.write (_stream_writable.js:291:5)\n    at WebSocketConnection.sendFrame (/homebridge/node_modules/websocket/lib/WebSocketConnection.js:859:31)\n    at WebSocketConnection.fragmentAndSend (/homebridge/node_modules/websocket/lib/WebSocketConnection.js:795:14)\n    at WebSocketConnection.sendUTF (/homebridge/node_modules/websocket/lib/WebSocketConnection.js:735:10)\n    at HarmonyHub.sendRequest (/homebridge/node_modules/harmonyhub-api/dist/HarmonyHub.js:275:23)\n    at HarmonyHub.sendCommand (/homebridge/node_modules/harmonyhub-api/dist/HarmonyHub.js:131:14)\n    at hub.connect.then (/homebridge/node_modules/homebridge-harmony-tv-smockle/index.js:203:14)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
(node:1349) UnhandledPromiseRejectionWarning: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:243:12)
    at Socket.Writable.write (_stream_writable.js:291:5)
    at WebSocketConnection.sendFrame (/homebridge/node_modules/websocket/lib/WebSocketConnection.js:859:31)
    at WebSocketConnection.fragmentAndSend (/homebridge/node_modules/websocket/lib/WebSocketConnection.js:795:14)
    at WebSocketConnection.sendUTF (/homebridge/node_modules/websocket/lib/WebSocketConnection.js:735:10)
    at HarmonyHub.sendRequest (/homebridge/node_modules/harmonyhub-api/dist/HarmonyHub.js:275:23)
    at HarmonyHub.sendCommand (/homebridge/node_modules/harmonyhub-api/dist/HarmonyHub.js:131:14)
    at hub.connect.then (/homebridge/node_modules/homebridge-harmony-tv-smockle/index.js:203:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by smockle** [comment]
@DavidSpek Thanks for reporting this! A couple questions—which version of Node.js are you running and which version of `homebridge-harmony-tv-smockle` do you have installed?

Regarding this:

> It seems like this is caused by parsing something that is already an object

Could you please share the value of `"commands"` in your `config.json`? I’m curious whether the `"action"` value in each command is a string or an object in your configuration.

**Comment by DavidSpek** [comment]
Sorry for the late response. I just did a new installation with node.js version 10.6.6 and homebridge-harmony-tv-smockle version 2.0.9. Initially I had the commands structured as follows: 
`"commands": [
                {
                    "action": {
                        "command": "0",
                        "type": "IRCommand",
                        "deviceId": "60943072"
                    },
                    "name": "Number0",
                    "label": "0"
                },`
For this structure the parsing was redundant. However now I have it structured as the instructions:
`"commands": [{
				"action": "{\"command\":\"0\",\"type\":\"IRCommand\",\"deviceId\":\"60943072\"}",
				"name": "Number0",
				"label": "0"
			},`

However when I send a command I still get a similar error:

`error: Connection failed to the websocket: Error: socket hang up
(node:69279) UnhandledPromiseRejectionWarning: Error: socket hang up
    at createHangUpError (_http_client.js:313:15)
    at Socket.socketCloseListener (_http_client.js:354:25)
    at Socket.emit (events.js:187:15)
    at TCP._handle.close (net.js:598:12)
(node:69279) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:69279) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:69279) UnhandledPromiseRejectionWarning: Error: timeout
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-harmony-tv-smockle/node_modules/harmonyhub-api/dist/HarmonyHub.js:334:40)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
(node:69279) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)`

**Comment by nicoduj** [comment]
Hi,
Not really sure, but I think you are using harmonyhub api which is XMPP based, did you explicitly allowed XMPP in harmony hub after latest firmware update ?

**Comment by nicoduj** [comment]
@smockle by the way, thank you for mentioning my plugin :)

**Comment by smockle** [comment]
@nicoduj Thanks for the suggestions! `homebridge-harmony-tv` uses [`harmonyhub-api`](https://github.com/JordanMartin/harmonyhub-api), which uses the Harmony WebSocket (not XMPP) API.

I noticed that your plugin ([`homebridge-harmony`](https://github.com/nicoduj/homebridge-harmony)) uses [`harmony-websocket`](https://github.com/lopelex/harmony-websocket). It’s possible that is a better Harmony WebSocket API client.

I can’t reproduce this error locally, and I’m wary of making changes I can’t test. If I publish a version of this plugin that uses `harmony-websocket` instead of `harmonyhub-api`, would anyone be interested in testing it?

**Comment by nicoduj** [comment]
Sorry for the confusion between the apis :) I checked the code, it was not updated to latest changes in latest revision of harmony hub firmware (http://localhost.nebula.myharmony.com still there :) ).

What is your firmware version on your hub ? Might be related I think. Changes were made in 4.15.250 (was fine in 4.15.210)

**Comment by smockle** [comment]
This is resolved in `homebridge-harmony-tv-smockle` version 2.0.11 and later.
